version: "3.9"
services:
  ms_config:
    container_name: ms_config
    image: ms_config:1.0.0
    build: ms-config/.
    ports:
      - "8888:8888"
    expose:
      - 8888
    networks:
      - ms_network
  ms_eureka:
    container_name: ms_eureka
    image: ms_eureka:1.0.0
    build: ms-eureka/.
    ports:
      - "8761:8761"
    networks:
      - ms_network
    links:
      - ms_config
    depends_on:
      - ms_config
    environment:
      - CONFIG_URI=http://172.19.0.2:8888
  ms_user_db:
    container_name: ms_user_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    networks:
      - ms_network
  ms_user:
    container_name: ms_user
    image: ms_user:1.0.0
    build: ms-user/.
    ports:
      - "8090:8090"
    networks:
      - ms_network
    links:
      - ms_config
      - ms_eureka
    depends_on:
      - ms_config
      - ms_eureka
      - ms_user_db
    environment:
      - CONFIG_URI=http://172.19.0.2:8888
      - EUREKA_URI=http://172.19.0.3:8761
      - DATABASE_URL=jdbc:postgresql://ms_user_db:5432/users_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
  ms_transfers_db:
    container_name: ms_transfers_db
    image: postgres:12
    expose:
      - 5435
    ports:
      - "5435:5435"
    command: -p 5435
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transfers_db
    networks:
      - ms_network
  ms_transfers:
    container_name: ms_transfers
    image: ms_transfers:1.0.0
    build: ms-transfers/.
    ports:
      - "8060:8060"
    networks:
      - ms_network
    links:
      - ms_config
      - ms_eureka
      - ms_user
    depends_on:
      - ms_config
      - ms_eureka
      - ms_transfers_db
    environment:
      - CONFIG_URI=http://172.19.0.2:8888
      - EUREKA_URI=http://172.19.0.3:8761
      - DATABASE_URL=jdbc:postgresql://ms_transfers_db:5435/transfers_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
networks:
  ms_network:
    driver: bridge