version: "3.9"

networks:
  ms_network:
    driver: bridge
    internal: true
  transactions_net:
    driver: bridge

services:
  ms_config:
    container_name: ms_config
    image: ms_config:1.0.0
    build: ms-config/.
    ports:
      - "8888:8888"
    expose:
      - 8888
    networks:
      ms_network:
        aliases:
          - microservice-config
  ms_eureka:
    container_name: ms_eureka
    image: ms_eureka:1.0.0
    build: ms-eureka/.
    ports:
      - "8761:8761"
    networks:
      ms_network:
        aliases:
          - microservice-eureka
    links:
      - ms_config
    depends_on:
      - ms_config
    environment:
      - CONFIG_URI=http://microservice-config:8888
  ms_user_db:
    container_name: ms_user_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    networks:
      - ms_network
#      - transactions_net
  ms_transfers_db:
    container_name: ms_transfers_db
    image: postgres:12
    expose:
      - 5435
    ports:
      - "5435:5435"
    command: -p 5435
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transfers_db
    networks:
      - ms_network
#      - transactions_net
  ms_auth_db:
    container_name: ms_auth_db
    image: postgres:12
    expose:
      - 5433
    ports:
      - "5433:5433"
    command: -p 5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    networks:
      - ms_network
#      - transactions_net
  cache:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - ms_network
#      - transactions_net
  ms_user:
    container_name: ms_user
    image: ms_user:1.0.0
    build: ms-user/.
    ports:
      - "8090:8090"
    networks:
      ms_network:
        aliases:
          - microservice-users
    links:
      - ms_config
      - ms_eureka
    depends_on:
      - ms_config
      - ms_eureka
      - ms_user_db
    environment:
      - CONFIG_URI=http://microservice-config:8888
      - EUREKA_URI=http://microservice-eureka:8761
      - DATABASE_URL=jdbc:postgresql://ms_user_db:5432/users_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
  ms_transfers:
    container_name: ms_transfers
    image: ms_transfers:1.0.0
    build: ms-transfers/.
    ports:
      - "8060:8060"
    networks:
      ms_network:
        aliases:
          - microservice-accounts
    links:
      - ms_config
      - ms_eureka
      - ms_user
      - cache
    depends_on:
      - ms_config
      - ms_eureka
      - ms_transfers_db
      - cache
    environment:
      - CONFIG_URI=http://microservice-config:8888
      - EUREKA_URI=http://microservice-eureka:8761
      - DATABASE_URL=jdbc:postgresql://ms_transfers_db:5435/transfers_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - SPRING_REDIS_HOST=cache
      - SPRING_REDIS_PORT=6379
  ms_auth:
    container_name: ms_auth
    image: ms_auth:1.0.0
    build: ms-auth/.
    ports:
      - "9898:9898"
    networks:
      ms_network:
        aliases:
          - microservice-auth
    links:
      - ms_config
      - ms_eureka
      - ms_user
    depends_on:
      - ms_config
      - ms_eureka
      - ms_user
      - ms_auth_db
    environment:
      - CONFIG_URI=http://microservice-config:8888
      - EUREKA_URI=http://microservice-eureka:8761
      - DATABASE_URL=jdbc:postgresql://ms_auth_db:5433/auth_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
  ms_gateway:
    container_name: ms_gateway
    image: ms_gateway:1.0.0
    build: ms-gateway/.
    ports:
      - "8080:8080"
    networks:
      - ms_network
      - transactions_net
    links:
      - ms_transfers
      - ms_user
      - ms_eureka
      - ms_auth
    depends_on:
      - ms_config
      - ms_eureka
      - ms_transfers
      - ms_user
      - ms_auth
    environment:
      - CONFIG_URI=http://microservice-config:8888
      - EUREKA_URI=http://microservice-eureka:8761
      - USERS_URI=http://microservice-users:8090
      - ACCOUNTS_URI=http://microservice-accounts:8060
      - AUTH_URI=http://microservice-auth:9898