server:
  port: 9898

spring:
  application:
    name: ms-auth
    title: MsAuth
    version: 1.0.0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddlAuto: update
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}/eureka