server:
  port: 8761

spring:
  application:
    name: ms-eureka
    title: MsEurekaServer
    version: 0.0.1

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serverUrl:
      defaultZone: http://localhost:${server.port}/eureka/